services:
  backend:
    build:
      context: ./v-backend
      dockerfile: Dockerfile
    ports:
      - '9000:9000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
